using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TNS.AdExpress.Constantes.Web
{
    /// <summary>
    /// Hello world, merci de trier par ordre numérique
    /// </summary>
    public class LanguageConstantes
    {
        #region Please insert any new code in the correct order
        
        public const long Cancel = 000;
        public const long NameCode = 67;
        public const long CompanyCode = 68;
        public const long CountryCode = 70;
        public const long PhoneNumberCode = 71;
        public const long CommentCode = 74;
        public const long MediaScheduleCode = 150;
        public const long MediaCode = 190;
        public const long DroppedSuccessfully = 286;
        public const long Media = 363;
        public const long QuestionTag3Code = 647;
        public const long CreateFolder = 696;
        public const long DropFolder = 697;
        public const long RenameFolderTitle = 698;
        public const long RenameNewFodler = 700;
        public const long SelectFolderToDelete = 701;
        public const long SelectFolder = 702;
        public const long RenameSelectedFolder = 703;
        public const long ErrorMsgNoFolderCreated = 711;
        public const long ModuleLabel = 760;
        public const long MonAdExpressCode = 761;
        public const long ContactLabelCode = 763;
        public const long ContactDescriptionCode = 764;
        public const long SaveUniversCode = 769;
        public const long LoadUniversCode = 770;
        public const long MyResultsDescription = 827;
        public const long ResultsCode = 829;
        public const long DroppingFailed = 830;
        public const long NoQueryErrorMsg = 831;
        public const long RequiredPermission = 832;
        public const long EmptyField = 837;
        public const long StudySelection = 842;
        public const long Unit = 849;
        public const long CantLoadSession = 851;
        public const long DownloadLabel = 874;
        public const long UserUniversCode = 875;
        public const long UserSavedUniversCode = 893;
        public const long MonAdExpressDescription = 904;
        public const long MoveSelectedResult = 911; 
        public const long SelectUniversGroup = 917;
        public const long ExceptionMsg = 922;
        public const long NoUniversGroup = 925;
        public const long NoSelectedUnivers = 926;
        public const long EmptyUnivers = 927;
        public const long NoSavedUniversCode = 930;
        public const long KeyWordLabelCode = 972;
        public const long Capacity = 1000;
        public const long SelectMedia=1017;
        public const long MediaRequiredCode = 1052;
        public const long MailCode = 1136;
        public const long Periodicity = 1293;
        public const long Monthly = 1294;
        public const long Quartly = 1295;
        public const long Insertion = 1400;
        public const long MediaSelected = 1487;
        public const long FileName = 1746;
        public const long AlertEmptyFields = 1748;
        public const long UniversProduct = 1759;
        public const long IncompleteDataForQuery = 1787;
        public const long LevelDetails = 1886;
        public const long CreativeLabel = 1888;
        public const long Save = 1990;
        public const long Export = 1992;
        public const long VisuelLabel = 1909;
        public const long JobTitleCode = 1976;
        public const long ExportFormattedResult = 1996;
        public const long ExportResultWithValue = 1997;
        public const long ExportGrossResult = 2014;
        public const long ExportPdfResult = 2017;
        public const long NotValidEmail = 2041;
        public const long RefineCode = 2053;
        public const long NewsLabel = 2080;
        public const long EmptyGrid = 2106;
        public const long PresentAbsentCode = 2167;
        public const long LostWonCode = 2169;
        public const long PortfolioCode = 2170;
        public const long PresentAbsentDescriptionCode = 2196;
        public const long LostWonDescriptionCode = 2198;
        public const long PortfolioDescriptionCode = 2199;
        public const long MediaScheduleDescriptionCode = 2200;
        public const long StudyPeriodCode = 2291;
        public const long ComparativePeriodCode = 2292;
        public const long ComparativePeriodTypeCode = 2293;
        public const long PeriodDisponibilityTypecode = 2296;
        public const long GenericLevelDetailColumnCode = 2300;
        public const long UniversSupport = 2540;
        public const long InsertionsLabel = 2245;
        public const long SelectUnivers = 2261;
        public const long ErrorOverLimit = 2264;//==> only 200 items
        public const long LimitUniverses = 2265;
        public const long UniversLabel = 2268;
        public const long ExcludeCode = 2269;
        public const long IncludeCode = 2270;
        public const long BranchLabelCode = 2272;
        public const long PeriodSelection = 2275;
        public const long ElementLabelCode = 2278;
        public const long DeleteAllcode = 2279;
        public const long IncludedElements = 2281;
        public const long ExcludedElements = 2282;
        public const long SecurityMsg = 2285;
        public const long OverLimitMsgCode = 2286;
        public const long KeyWordDescriptionCode = 2287;
        public const long MininumInclude = 2299;
        public const long Close = 2371;
        public const long NotAvailableSession = 2455;
        public const long Receiver = 2483;
        public const long UnityError = 2541;
        public const long PreSelection = 2571;
        public const long CreateAlert = 2578;
        public const long Daily = 2579;
        public const long Weekly = 2580;
        public const long SaveAlert = 2581;
        public const long SelectDayInWeek = 2582;
        public const long SelectDayInMonth = 2583;
        public const long AlertsCode = 2585;
        public const long NoAlerts = 2587;
        public const long SendDate = 2588;
        public const long Occurrence = 2600;
        public const long Occurrences = 2601;
        public const long AlertDetails = 2602;
        public const long Deadline = 2603;
        public const long EveryWeek = 2604;
        public const long EveryMonth = 2605;
        public const long ExpirationDate = 2606;
        public const long AlertType = 2607;
        public const long SaveAlert2 = 2609;
        public const long TimeSchedule = 2614;
        public const long MaxAlertLimit = 2615;
        public const long AlertInfoMessage = 2616;
        public const long AlertCreationSucceeded = 2660;
        public const long Concurrent = 2869;
        public const long Dates = 2882;
        public const long IndeRadioMessage = 3018;
        public const long ExportPptResult = 3031;
        public const long LimitKeyword = 3033;
        public const long ItemExceeded = 3034;
        public const long NoSupport = 3035;
        public const long ErrorOnlyOneItemAllowed = 3036;
        public const long AddConcurrentCode = 3037;
        public const long SupportAlreadyDefine = 3038;
        public const long Referent = 3039;
        public const long Submit = 3040;
        public const long QuestionTagCode = 3041;
        public const long QuestionTag1Code = 3042;
        public const long QuestionTag2Code = 3043;
        public const long Results = 3044;
        public const long Directories = 3045;
        public const long NotAvailableYet = 3046;
        public const long HomeCode = 3047;
        public const long Market = 3048;
        public const long YourModule = 3051;
        public const long NewsDescr = 3052;
        public const long ContactUsLabel = 3055;
        public const long EveryDay = 000000;
        public const long MoveResultTitle = 00000;
        #endregion
    }
}
