//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace TNS.AdExpressI.Visual.WebService.CreativeView {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreativeViewSoap", Namespace="http://tempuri.org/")]
    public partial class CreativeView : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBinariesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIsExistOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreativeView() {
            this.Url = global::TNS.AdExpressI.Visual.WebService.Properties.Settings.Default.TNS_AdExpressI_Visual_WebService_CreativeView_CreativeView;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBinariesCompletedEventHandler GetBinariesCompleted;
        
        /// <remarks/>
        public event GetIsExistCompletedEventHandler GetIsExistCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBinaries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetBinaries(string relativePath, long idVehicle, bool isBlur, bool isCover) {
            object[] results = this.Invoke("GetBinaries", new object[] {
                        relativePath,
                        idVehicle,
                        isBlur,
                        isCover});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBinariesAsync(string relativePath, long idVehicle, bool isBlur, bool isCover) {
            this.GetBinariesAsync(relativePath, idVehicle, isBlur, isCover, null);
        }
        
        /// <remarks/>
        public void GetBinariesAsync(string relativePath, long idVehicle, bool isBlur, bool isCover, object userState) {
            if ((this.GetBinariesOperationCompleted == null)) {
                this.GetBinariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBinariesOperationCompleted);
            }
            this.InvokeAsync("GetBinaries", new object[] {
                        relativePath,
                        idVehicle,
                        isBlur,
                        isCover}, this.GetBinariesOperationCompleted, userState);
        }
        
        private void OnGetBinariesOperationCompleted(object arg) {
            if ((this.GetBinariesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBinariesCompleted(this, new GetBinariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIsExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetIsExist(string relativePath, long idVehicle, bool isCover) {
            object[] results = this.Invoke("GetIsExist", new object[] {
                        relativePath,
                        idVehicle,
                        isCover});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetIsExistAsync(string relativePath, long idVehicle, bool isCover) {
            this.GetIsExistAsync(relativePath, idVehicle, isCover, null);
        }
        
        /// <remarks/>
        public void GetIsExistAsync(string relativePath, long idVehicle, bool isCover, object userState) {
            if ((this.GetIsExistOperationCompleted == null)) {
                this.GetIsExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIsExistOperationCompleted);
            }
            this.InvokeAsync("GetIsExist", new object[] {
                        relativePath,
                        idVehicle,
                        isCover}, this.GetIsExistOperationCompleted, userState);
        }
        
        private void OnGetIsExistOperationCompleted(object arg) {
            if ((this.GetIsExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIsExistCompleted(this, new GetIsExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBinariesCompletedEventHandler(object sender, GetBinariesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBinariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBinariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIsExistCompletedEventHandler(object sender, GetIsExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIsExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIsExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591